# General  
train_2d: False
no_eval: False
finetune: True
partial_train: null

# Traning 
epochs: 250
checkpoint_frequency: 30
batch_size: 4
accumulate_gradients: 8
num_workers: 8
dropout: 0.0
learning_rate: 0.0002
weight_decay: 0.01
lr_decay: 0.995

# Model
maxlen: 243
dim_feat: 512
mlp_ratio: 2
depth: 5
dim_rep: 512
num_heads: 8
att_fuse: True

# Data
dataset: skipose
data_root: /scratch/rhti/notafork/data/Ski-PosePTZ-CameraDataset-png
subset_list: []
dt_file: h36m_sh_conf_cam_source_final.pkl
clip_len: 243
data_stride: 81
rootrel: True
sample_stride: 1
num_joints: 17
no_conf: False
gt_2d: False
train_views: [0,1,2,3, 4, 5]

# Loss
mpjpe_weight: 0.0
lambda_3d_velocity: 20.0
lambda_scale: 0.0
lambda_lv: 0.0
lambda_lg: 0.0
lambda_a: 0.0
lambda_av: 0.0
lambda_consistency: 0.3
mpjpe_2d_weight: 1.0

# Augmentation
synthetic: False
flip: True
mask_ratio: 0.
mask_T_ratio: 0.
noise: False
